import type { ProviderPreset } from '@/features/models/types';

export const MODEL_PROVIDER_PRESETS: ProviderPreset[] = [
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://api.deepseek.com/v1',
    description: 'Reasoning and general chat models from DeepSeek.',
    docsUrl: 'https://platform.deepseek.com/',
    id: 'deepseek',
    logoId: 'deepseek',
    models: [],
    monogram: 'DS',
    name: 'DeepSeek',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://api.openai.com/v1',
    description: 'GPT series via the standard OpenAI-compatible API.',
    docsUrl: 'https://platform.openai.com/docs',
    id: 'openai',
    logoId: 'openai',
    models: [],
    monogram: 'OA',
    name: 'OpenAI',
  },
  {
    apiFormat: 'anthropic',
    defaultBaseUrl: 'https://api.anthropic.com/v1',
    description: 'Claude models using the Anthropic protocol.',
    docsUrl: 'https://docs.anthropic.com/',
    id: 'anthropic',
    logoId: 'anthropic',
    models: [],
    monogram: 'CL',
    name: 'Anthropic',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    description: 'Gemini models through the OpenAI-compatible endpoint.',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/openai',
    id: 'google',
    logoId: 'google',
    models: [],
    monogram: 'GM',
    name: 'Google',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://api.x.ai/v1',
    description: 'Grok models from xAI via OpenAI-compatible API.',
    docsUrl: 'https://docs.x.ai/',
    id: 'xai',
    logoId: 'xai',
    models: [],
    monogram: 'x',
    name: 'xAI',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    description: 'Fast inference for open-weight and hosted models.',
    docsUrl: 'https://console.groq.com/docs/overview',
    id: 'groq',
    logoId: 'groq',
    models: [],
    monogram: 'GQ',
    name: 'Groq',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    description: 'Single endpoint for multiple commercial and open providers.',
    docsUrl: 'https://openrouter.ai/docs',
    id: 'openrouter',
    logoId: 'openrouter',
    models: [],
    monogram: 'OR',
    name: 'OpenRouter',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    description: 'Mistral-hosted frontier and open-weight models.',
    docsUrl: 'https://docs.mistral.ai/',
    id: 'mistral',
    logoId: 'mistral',
    models: [],
    monogram: 'MS',
    name: 'Mistral',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://api.cohere.ai/compatibility/v1',
    description: 'Command models through the OpenAI compatibility API.',
    docsUrl: 'https://docs.cohere.com/docs/compatibility-api',
    id: 'cohere',
    logoId: 'cohere',
    models: [],
    monogram: 'CH',
    name: 'Cohere',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
    description: 'Moonshot and Kimi models.',
    docsUrl: 'https://platform.moonshot.cn/docs',
    id: 'moonshot',
    logoId: 'moonshotai',
    models: [],
    monogram: 'K',
    name: 'Moonshot',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    description: 'Qwen family via DashScope compatibility API.',
    docsUrl: 'https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope',
    id: 'qwen',
    logoId: 'alibaba',
    models: [],
    monogram: 'QW',
    name: 'Qwen',
  },
  {
    apiFormat: 'openai',
    defaultBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    description: 'GLM models from Zhipu AI.',
    docsUrl: 'https://open.bigmodel.cn/dev/howuse/introduction',
    id: 'zhipu',
    logoId: 'zhipuai',
    models: [],
    monogram: 'ZP',
    name: 'Zhipu',
  },
];
