export const AI_CONFIG = {
  AGENT_MAX_STEPS: 10,
  CHAT_MAX_DURATION: 60,
  DEFAULT_MAX_TOKENS: 800,
  MEMORY_EXTRACTION_MAX_OUTPUT_TOKENS: 220,
  SUMMARY_MAX_OUTPUT_TOKENS: 220,
  TITLE_MAX_OUTPUT_TOKENS: 32,
} as const;

export const CHAT_UI_CONFIG = {
  INVALID_CONVERSATION_RESET_DELAY_MS: 350,
  MEMORY_SETTINGS_INPUT_DEBOUNCE_MS: 600,
  POST_FINISH_REFRESH_DELAY_MS: 1200,
  SAVE_FEEDBACK_DURATION_MS: 1400,
  SIDEBAR_SEARCH_DEBOUNCE_MS: 250,
} as const;

export const CONVERSATION_SIDEBAR_PAGE_SIZE = 20;
