export const PAGINATION_CONFIG = {
  CONVERSATIONS_MAX_LIMIT: 50,
  CONVERSATIONS_MAX_OFFSET: 10_000,
} as const;

export const TEXT_LIMITS = {
  CONVERSATION_PREVIEW: 120,
  CONVERSATION_SUMMARY: 4000,
  CONVERSATION_TITLE: 100,
  GENERATED_SUMMARY: 1200,
  GENERATED_TITLE: 60,
  INITIAL_MESSAGE: 10_000,
  MEMORY_CONTENT: 280,
} as const;
