export const MEMORY_CONFIG = {
  CONTEXT_MAX_ITEMS: 20,
  SAVED_MEMORIES_PAGE_SIZE: 6,
  SUMMARY_MIN_MESSAGES: 4,
  SUMMARY_RECENT_MESSAGE_WINDOW: 10,
} as const;

export const MEMORY_EXTRACTION_CONFIG = {
  FALLBACK_MAX_OUTPUT_TOKENS: 220,
  MAX_CONTENT_LENGTH: 280,
  MAX_ITEMS: 3,
  MIN_MESSAGES: 2,
  TRANSCRIPT_MESSAGE_WINDOW: 12,
} as const;

export const MEMORY_CONSOLIDATION_CONFIG = {
  MAX_ITEMS_PER_KIND: 3,
  SOURCE_ITEMS_LIMIT: 12,
  THRESHOLDS: {
    fact: 5,
    preference: 5,
    profile: 5,
    workflow: 5,
  },
} as const;
