export const MEMORY_CONFIG = {
  CONTEXT_MAX_ITEMS: 4,
  SUMMARY_MIN_MESSAGES: 8,
  SUMMARY_RECENT_MESSAGE_WINDOW: 10,
} as const;

export const MEMORY_EXTRACTION_CONFIG = {
  FALLBACK_MAX_OUTPUT_TOKENS: 220,
  MAX_CONTENT_LENGTH: 280,
  MAX_ITEMS: 3,
  MIN_MESSAGES: 2,
  TRANSCRIPT_MESSAGE_WINDOW: 12,
} as const;
