export const RAG_CONFIG = {
  CHUNK_OVERLAP_CHARACTERS: 150,
  CHUNK_SIZE_CHARACTERS: 1000,
  DEFAULT_EMBEDDING_MODEL: 'voyage-4-lite',
  DEFAULT_MATCH_COUNT: 4,
  DEFAULT_MATCH_THRESHOLD: 0.2,
  DEFAULT_MAX_CONTEXT_CHARACTERS: 5000,
  EMBEDDING_DIMENSIONS: 1024,
  IMPORT_PREVIEW_CHARACTERS: 240,
  MAX_CONTEXT_CHARACTERS: 12000,
  MAX_FILE_BYTES: 10 * 1024 * 1024,
  MAX_MATCH_COUNT: 8,
} as const;
