export const SANDBOX_CONFIG = {
  DEFAULT_TEMPLATE: 'base',
  DEFAULT_TIMEOUT_SECONDS: 300,
  TIMEOUT_MIN_SECONDS: 60,
  TIMEOUT_MAX_SECONDS: 3600,
  DEFAULT_WORKING_DIRECTORY: '/workspace',
  DEFAULT_ENV_VARS_TEXT: '',
} as const;
